/// Flutter icons Qr_code_ico
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Qr_code_ico
///      fonts:
///       - asset: fonts/Qr_code_ico.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class Qr_code_ico {
  Qr_code_ico._();

  static const _kFontFam = 'Qr_code_ico';
  static const _kFontPkg = null;

  static const IconData qrcode = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
